Repository tanishap11/TMC, pull requests merged in 2019-10, with the labels that each got.

#2 added an html file
  claudia.html
  tExT.txt
Labels: documentation

#5 added a file by cc
  hello.txt
  information.txt
Labels: documentation

#6 added a celebration text
  IFINALLYGETIT.txt
Labels: enhancement

#7 Mathieu
  WEGOTTHIS
  WEGOTTHIS.html
Labels: documentation

#9 moreeee stuff
  lastfileoftheday.txt
Labels: documentation

#10 added contributors section
  Contributors.html
Labels: help wanted

#12 directions to store updated
  Directions.html
Labels: good first issue
